### PR TITLE
Add some Adobe icons

### PR DESCRIPTION
**Pull request by xmha97**

### CODE REVIEW

**Comment by FadeMind** [comment]
@xmha97  follow current folder orders. No mess up.

**Comment by xmha97** [comment]
All the icons in the "ICO" folder correspond to Windows icons.

In the "Adobe ICO" folder, I will put the main icons of Adobe apps, and these icons cannot be placed in any of the existing folders. For example, Adobe folders are not the same as any Windows folders.

Mess up occurs when I will combine these two folders.

Also, I have contributed a lot to this project so far and will continue to do so, and I never want this project to be ruined.

**Comment by xmha97** [comment]
All the icons in the "ICO" folder correspond to Windows icons.

In the "Adobe ICO" folder, I will put the main icons of Adobe apps, and these icons cannot be placed in any of the existing folders. For example, Adobe folders are not the same as any Windows folders.

Mess up occurs when I will combine these two folders.

Also, I have contributed a lot to this project so far and will continue to do so, and I never want this project to be ruined.

cc: @FadeMind

**Comment by FadeMind** [comment]
Paste new icons in PATH `W-ICO\ICO\Apps (Windows 11)\Adobe`.

**Comment by xmha97** [comment]
> W-ICO\ICO\Apps (Windows 11)\Adobe

@FadeMind Done.

**Pull request merged**
