### PR TITLE
Add numbering to folders names

### PR DESCRIPTION
**Pull request by xmha97**
image

### CODE REVIEW

**Comment by FadeMind** [comment]
@xmha97What will this change bring besides numbers in the name? I don't see the need to change the folder names again.

**Comment by xmha97** [comment]
> I don't see the need to change the folder names again.

Adding numbers to folder names helps sort folders:
```
 _______________      _______________
| Windows 7     |    | Windows 98    |
| Windows 10    |    | Windows XP    |
| Windows 98    | -> | Windows Vista |
| Windows Vista |    | Windows 7     |
| Windows XP    |    | Windows 10    |
 ---------------      ---------------
```

**Comment by xmha97** [comment]
Ok, creating subfolders:
Folder\01 Windows 98
Folder\01 Windows XP
Folder\01 Windows Vista
Folder\01 Windows 7
Folder\01 Windows 10
Is it good?

**Comment by FadeMind** [comment]
For me current naming folders is just fine. Everyone can handle it. Several month ago was same "issue". EOT

**Comment by xmha97** [comment]
> For me current naming folders is just fine. Everyone can handle it. Several month ago was same "issue". EOT

Okay, sorry if our tastes did not match.
I will add new icons with the same structure.

**Pull request closed without merging**
