### PR TITLE
Classify Icons

### PR DESCRIPTION
**Pull request by xmha97**
Move all icons to Icons folder

### CODE REVIEW

**Comment by xmha97** [comment]
@FadeMind If you want to merge this PR.

**Comment by FadeMind** [comment]
@xmha97 revert Icons folder - not needed here at all. I will merge only new icons.

**Comment by xmha97** [comment]
> @xmha97 revert Icons folder - not needed here at all. I will merge only new icons.

Sorry, I should have mentioned my reason for doing this before PR.
Day by day the folders that are on the first page (root folder) are increasing and this is not good because after scrolling, you will see the README.md file.
I want to users see the screenshot file so they can understand at a glance what this repository is.

image

**Comment by xmha97** [comment]
Hi @FadeMind 
Sorry, I should have mentioned my reason for doing this before PR.
Day by day the folders that are on the first page (root folder) are increasing and this is not good because after scrolling, you will see the README.md file.
I want to users see the screenshot file so they can understand at a glance what this repository is.

image

**Comment by FadeMind** [comment]
@xmha97 please  use fresh fork and make proper changes ONLY for adding new icons. I moved icons to root dir `ICO`.

**Comment by xmha97** [comment]
Ok, Thanks 🙏

**Pull request closed without merging**
