### PR TITLE
Add some new icons

### PR DESCRIPTION
**Pull request by xmha97**

### CODE REVIEW

**Comment by xmha97** [comment]
cc: @FadeMind Please merge this PR; Thanks.

**Comment by FadeMind** [comment]
@xmha97 what was  removed here? I see some R in log :>

**Comment by xmha97** [comment]
> @xmha97 what was removed here? I see some R in log :>

I removed the following because it was repetitive:

image

Now let's check these things:

image

Available at this address:
```
"W-ICO\ICO\Drive (Windows 11)\Floppy.ico"
```

image

Available at this address:
```
"W-ICO\ICO\Drive (Windows 11)\ICON29_1.ico"
```

image

Available at this address:
```
"W-ICO\ICO\Drive (Windows 11)\CD Disk.ico"
```

image

Available at this address:
```
"W-ICO\ICO\Drive (Windows 11)\DVD.ico"
```

image

Available at this address:
```
"W-ICO\ICO\Drive (Windows 11)\ICON42_1.ico"
```

It would have been better if I had done the deletions in a separate commit and explain them.

**Comment by FadeMind** [comment]
@xmha97 thanks. Merging.

**Pull request merged**
